### ISSUE TITLE
Create file where we can redefine all input and output ports

### ISSUE THREAD

**Issue by richarthurs** [SFUSatClub/obc-firmware#16]
Right now we've got SPI config structs and GIO pin macros all over the place. It would be nice to have those all in one file, where we could easily redefine them without having to dig around driver and application code. 

Example: RTC.c has a GIO set for CS, using the gioPORTA macro. We should change that to a new macro, called RTC_CS or something, and define RTC_CS as gioPORTA somewhere else so we can change it easily if we need to.

**Comment by liquiddandruff** [comment]
Good idea, will be a good beginner task.
