### ISSUE TITLE
Test safety features of TMS570 and incorporate into system (self-checkup procedures on boot, etc)

### ISSUE THREAD

**Issue by liquiddandruff** [SFUSatClub/obc-firmware#18]

**Comment by richarthurs** [comment]
- Enable CCM (core compare module) in HALCoGen (won’t run in debug mode)
- Get self test pass/fail information out from the tests (currently they just loop forever on failure)
- Write a test suite to inject failure in self test module, see if we can detect them
- sfu_startup.h

**Comment by richarthurs** [comment]
Here are some more details:

- enable self tests at startup (halocogen, sys_startup.c, sys_selfcheck.c,  sfu_startup.c)
- once we get into our software, we should be checking the values of the self check error registers, such as FSRC0 and logging them to a file. We should check the registers for every self test that we perform. 
- TRM section 7 and 8

Beyond self tests, there is ECC memory. There are registers that count the number of corrected errors and things like that.
- enable anything required for this functionality (halcogen)
- figure out which registers to look at (TRM pg. 302 is a starting point)
- Write a function to check these registers. We will periodically run this during operation

TRM: http://www.ti.com/lit/ug/spnu607a/spnu607a.pdf

**Comment by richarthurs** [comment]
This library might also have examples of how to do some of the things we're interested in: http://www.ti.com/tool/SAFETI_DIAG_LIB

**Comment by slanab** [comment]
Merged to master in 5f17ecbc846132de075e18b03c943acb586ad9d6
