### ISSUE TITLE
RTC assert fails without RTC plugged in

### ISSUE THREAD

**Issue by richarthurs** [SFUSatClub/obc-firmware#28]
The convertBCD function uses an assert to work correctly. Therefore, when the RTC is broken or not plugged in, the assert will crash the system.

**Comment by richarthurs** [comment]
To fix: find another way to convert BCD>Decimal, or create a flag so this won't run if the RTC has not initialized properly.

**Comment by victormleon** [comment]
Branch `victor/convertBCD-28` made for this issue.
