### ISSUE TITLE
Turn down the clock

### ISSUE THREAD

**Issue by richarthurs** [SFUSatClub/obc-firmware#40]
We're not going to be running in space at 160 MHz, so don't run on Earth at that speed.

In HALCoGen set to 80 MHz

**Comment by richarthurs** [comment]
Changed to 60 MHz for 0.3 and 0.4 configs. Launchpad still runs at 80. 

e6e313d08cdf278e43504c4df373eb400f5431b3

**Comment by liquiddandruff** [comment]
What branch is hash e6e313d08cdf278e43504c4df373eb400f5431b3 in? I can't seem to find it.

Current head of branch radio (our current latest changes) has "#define RTI_CLK_SPEED_HZ		30000000	// 30 MHz - for RTOS tick" still in `sfu_hardwaredefs.h`, so not sure this change has been made yet.

**Comment by richarthurs** [comment]
Oh I haven't pushed it yet I think.
