### ISSUE TITLE
Linker Command File is Old 

### ISSUE THREAD

**Issue by richarthurs** [SFUSatClub/obc-firmware#48]
I was seeing our RAM usage approach 70% ... which seems too high. Upon further inspection, the linker command files are identical between launchpad, 0.3, 0.4 configs. This is bad since the launchpad uses a really wussy chip, so the address spaces are much smaller than on the 0714. 

Todo: generate a new project with halcogen for 0714PGE + RTOS, grab that linker cmd file. 

It's weird that this isn't re-generated by halcogen...

**Comment by liquiddandruff** [comment]
This was one of the first things I noticed too, but haven't investigated it further than opening up the memory map view and finding nothing amiss. Nice catch with the linker file, it seems likely an issue with the addresses used then.

**Comment by richarthurs** [comment]
fixed in 841a5637ee06549431b0ec2b56504ce7d53424f9
