### ISSUE TITLE
Define TASK_IDs as unique magical identifiers instead of consecutive enums as they are now

### ISSUE THREAD

**Issue by liquiddandruff** [SFUSatClub/obc-firmware#57]
Much like the move from cmd id enums to magic identifers as in commit c98310ec72fc9e 

Current implementation (defined in `sfu_cmds.h`).
```
typedef enum TASK_IDS {
	TASK_MAIN,
	TASK_RADIO,
	TASK_TICKLE,
	/**
	 * The following tasks are used only in development and not in release.
	 * They may be #ifdef'd out or removed in the future.
	 */
	TASK_SERIAL,
	TASK_BLINKY,
	TASK_NUM_IDS,
} TASK_ID;
```

**Comment by mathison54** [comment]
Hi,
I could work on this if you like. So just needed to change it from enums to defines?
About TASK_SERIAL, TASK_BLINKY and TASK_NUM_IDS, I would put them under #idfedef, could it be "_DEBUG"?

**Comment by liquiddandruff** [comment]
Hi Adriano, we'd definitely appreciate your help! Yes, from enums to defines similar to the commit linked. 

Regarding the two task IDs originally meant for debug (TASK_NUM_IDS is a count and not a task id), TASK_SERIAL is to be used in release as well now, and there may be things depending on TASK_BLINKY, so just copy things over as is and update the comment (don't bother with ifdef).
