### ISSUE TITLE
Figure out why LED in Blinky task does not blink

### ISSUE THREAD

**Issue by liquiddandruff** [SFUSatClub/obc-firmware#6]
The Port A GPIO 2 is connected on the dev board to an LED. This LED previously blinks, but now on my dev board it does not. Last I remember it blinking properly was when I was working on getting the ADC readings from the light sensor: e01e1abe. 

I don't believe the halcogen GPIO config has been changed, so I wonder if this is an isolated incident and I've shorted my board or something. The relevant location to check would be the Blinky task implemented in https://github.com/SFUSatClub/obc-firmware/blob/master/SFUsat/sfu_tasks.c#L9 and the GIO pin settings in halcogen.

**Comment by cfinniga** [comment]
The board seems to work with the other code base so it's probably a problem with the code.
