### ISSUE TITLE
Poll MISO for CHIP_RDYn

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/obc-firmware#62]
Per CC1101 application note [DN503](http://www.ti.com/lit/an/swra112b/swra112b.pdf) section 4:
"After pulling CSn, one should always wait for the MISO to go low (CHIP_RDYn), before writing
the address header. The CHIP_RDYn signal indicates that the crystal is running and the
regulated digital supply voltage is stable. "

Currently a constant delay of 200ns is set from CSn low to start of data. This parameter is set in halcogen.

**Comment by richarthurs** [comment]
@liquiddandruff can this be closed?
